# plot(density(df$prev), type="n", xlab="number of previous appointments", ylab="numbe of observations")
# rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "#e5e5e5")
# grid(col="white", lwd=2)
# points(density(df$prev), col="#f8766d", lwd=2)
# df$hel <- ifelse(is.nan(df$noprevpct), 0, df$noprevpct)
# noprevtable <- table(ifelse(df$hel>=0.5,1,0),df$noshow)
# dimnames(noprevtable) <- list(c("mode0:", "mode1:"), c("show", "noshow"))
# prop.table(noprevtable,1)
# burstab <- prop.table(table(df$burs, df$noshow),1)
# dimnames(burstab) = list(c("no scholarship", "scholarship"), c("show", "no show"))
# burstab
# hipertab <- prop.table(table(df$hiper, df$noshow),1)
# dimnames(hipertab) = list(c("no hipertension", "hipertension"), c("show", "no show"))
# hipertab
# diabettab <- prop.table(table(df$diabet, df$noshow),1)
# dimnames(diabettab) = list(c("no diabetes", "diabetes"), c("show", "no show"))
# diabettab
# alcoholtab <- prop.table(table(df$alcohol, df$noshow),1)
# dimnames(alcoholtab) = list(c("no alcohol", "alcohol"), c("show", "no show"))
# alcoholtab
# handcaptab <- prop.table(table(df$handcap, df$noshow),1)
# dimnames(handcaptab) = list(c("handicap0:", "handicap1:", "handicap2:", "handicap3:", "handicap4:"), c("show", "no show"))
# handcaptab
# hist(df$daybw)
# hist(df$wdayap)
# hist(df$wdaysc)
# hourXnoshow <- table(df$hoursc, df$noshow)
# plot(sort(unique(df$hoursc)), hourXnoshow[,2]/(hourXnoshow[,1]+hourXnoshow[,2]))
# ageXnoshow <- table(df$age, df$noshow)
# plot(0,xlim=c(0,115),ylim=c(0.7,1),type = "n")
# rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "#e5e5e5")
# grid(col="white", lwd=2)
# lines(sort(unique(df$age)), ageXnoshow[,1]/(ageXnoshow[,1]+ageXnoshow[,2]), col="#f8766d", lwd=2)
# lines(prop.table(rowsum(ageXnoshow, c(1:81, rep(82,22))),1)[,1], type="l")
# legend(x="topleft", legend = c("all ages", "aggregate age>80"), fill = c("#f8766d", "black") )
# bwXnoshow <- table(df$daybw, df$noshow)
# plot(df$daybw, bwXnoshow)
# sexXnoshow <- table(df$male, df$noshow)
# plot(sexXnoshow[,1]/(sexXnoshow[,1]+sexXnoshow[,2]))
# rayonXnoshow <- table(df$rayon, df$noshow)
# plot(unique(df$rayon),rayonXnoshow[,1]/(rayonXnoshow[,1] + rayonXnoshow[,2]),type = "n", ylab="probability of showing up", xlab="Vitoria neighbourhood")
# rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "#e5e5e5")
# grid(col="white", lwd=2)
# lines(unique(df$rayon), prop.table(rayonXnoshow,1)[,1], type="h", lwd=4, col="#f8766d")
# lines(unique(df$rayon), rayonXnoshow[,2], type="h", lwd=7, col="#949494")
# plot(df$rayon,type = "n", ylab="number of data points", xlab="Vitoria neighbourhoods")
# sexXage <- table(df$age, df$male)
# plot(sexXage[,1], type="h", col="red")
# lines(sexXage[,2], col="blue")
# plot(table(df$wdaysc, df$noshow)[,2],type='n',ylim=c(0,0.25), xlab="days of week", ylab="probability of no-show")
# rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "#e5e5e5")
# grid(col="white", lwd=2)
# lines(prop.table(table(df$wdayap,df$noshow),1)[,2], type="o", col="blue", lwd=5)
# lines(prop.table(table(df$wdaysc,df$noshow),1)[,2], type="o", col="#f8766d", lwd=5)
# legend(x="bottomleft", legend = c("weekday of schedule", "weekday of appointment"), fill = c("blue", "#f8766d") )
# plot(table(df$wdaysc, df$noshow)[,2],type='n',ylim=c(0,0.25), xlab="days of week", ylab="probability of no-show")
# rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "#e5e5e5")
# grid(col="white", lwd=2)
# lines(prop.table(table(df$wdayap,df$noshow),1)[,2], type="o", col="blue", lwd=5)
# lines(prop.table(table(df$wdaysc,df$noshow),1)[,2], type="o", col="#f8766d", lwd=5)
# legend(x="bottomleft", legend = c("weekday of schedule", "weekday of appointment"), fill = c("blue", "#f8766d") )
# daybwXnoshow <- table(df$daybw, df$noshow)
# plot(prop.table(daybwXnoshow,1)[,2], type="n", xlab="# wait days", ylab="probability of no-show")
# rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "#e5e5e5")
# grid(col="white", lwd=2)
# lines(prop.table(daybwXnoshow,1)[,2], type="h", col="#f8766d", lwd=5)
# daybwgroup <- c(1:67, rep(68,62))
# #daybwgroup <- c(1, rep(2,100), rep(3,28))
# prop.table(rowsum(daybwXnoshow, daybwgroup),1)
# plot(prop.table(daybwXnoshow,1)[,2], type="h")
# lines(prop.table(rowsum(daybwXnoshow,daybwgroup),1)[,2], type="l")
# plot(prop.table(table(df$daybw, df$noshow),1)[,2], type="n")
# rect(par("usr")[1], par("usr")[3], par("usr")[2], par("usr")[4], col = "#e5e5e5")
# grid(col="white", lwd=2)
# lines(prop.table(table(df$daybw, df$noshow),1)[,2], type="h", col="#f8766d", lwd=3)
# sexXnoshow <- table(df[df$age<18,]$male, df[df$age<18,]$noshow)
# sexXnoshow
# prop.table(sexXnoshow,1)
# df <- df[!df$rayon %in% names(subset(table(df$rayon),table(df$rayon)<40)),]
# df$rayon <- factor(df$rayon)
# length(c(0, rep(1:7,each=4), rep(8:10,each=30), rep(10,10)))